apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
  labels:
    app: mysql
    app.kubernetes.io/name: mysql
  namespace: database  
data:
  primary.cnf: |
    # Apply this config only on the primary.
    [mysqld]
    server-id=1
    log-bin=mysql-bin
    binlog-format=ROW
    enforce-gtid-consistency=ON
    gtid-mode=ON
    skip-name-resolve
    character-set-server=utf8mb4
    collation-server=utf8mb4_unicode_ci
    max_connections=200
    default_authentication_plugin=mysql_native_password    
  replica.cnf: |
    # Apply this config only on replicas.
    [mysqld]
    server-id=2
    log-bin=mysql-bin
    relay-log=mysql-relay-bin
    binlog-format=ROW
    enforce-gtid-consistency=ON
    gtid-mode=ON
    read-only=ON
    skip-name-resolve
    character-set-server=utf8mb4
    collation-server=utf8mb4_unicode_ci
    max_connections=200
    default_authentication_plugin=mysql_native_password   